### ISSUE TITLE
Esegui eliminabile

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/vue-app#14]
Mi aspetterei che il pulsante esegui sia sempre presente durante l’attività di programmazione, ma posso eliminarlo quando definisco una attività.

**Comment by avivace** [comment]
Quindi, la minima condizione da raggiungere per avere un'attività valida e salvabile:

- ci deve essere almeno (o esattamente?) un pulsante che abbia l'azione "Esegui programma" assegnata

Ha senso?

**Comment by leonardo77** [comment]
Se c'è l'ambiente di programmazione deve esserci un pulsante di esegui. In futuro si potrebbe arrivare a definire attività prive dell'ambiente di programmazione, ad esempio solamente con la parte di controllo.
