### ISSUE TITLE
Editing dei valori imperfetto

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/vue-app#18]
Nel mio ambiente (Firefox su Mac) quando edito un dato all’interno di un programma blackly vedo il dato che sto scrivendo sovrapposto al dato che c'era già. Il risultato è che quello che si scrive risulta essere poco leggibile. Una volta confermata la modifica, il dato è ben visibile.

**Comment by leonardo77** [comment]
Oggi uno dei beta user mi ha detto di avere anche lui questo problema consistentemente su più browser e anche su iPad!

**Comment by avivace** [comment]
See https://github.com/CoderBotOrg/vue-app/issues/43#issuecomment-480977188
