### ISSUE TITLE
Setup parametri tecnici nella UI di studente e professore

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/vue-app#20]
Lasciare allo studente ma anche al professore/genitore la possibilità di editare parametri come:
- Parametri motori 
- Setup pulsante fisico (che credo non esista)
- Script da caricare all’avvio

Mi spaventa molto. Introdurrei un punto di ingresso per l'admin (che all'occorrenza può essere anche il professore/genitore) che può editarli e li toglierei dalle UI di studente e professore.

**Comment by avivace** [comment]
Questi settaggi sono attualmente nelle _Impostazioni_. Sarebbe sufficiente bloccare l'accesso alle  impostazioni al livello utente base?

**Comment by previ** [comment]
Ora c'è una password (facoltativa) per proteggere la parte "impostazioni".
