### ISSUE TITLE
Creazione attività

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/vue-app#24]
Dopo aver salvato una attività l’utente potrebbe credere che sia effettivamente in uso, ma non è così. Bisogna tornare sul menù delle attività e andarla ad aprirla per utilizzarla. Probabilmente varrebbe la pena chiedere all'utente subito dopo aver salvato una attività se vuole utilizzarla subito.

**Comment by previ** [comment]
Il comportamento attuale effettivamente è migliorabile.

Al momento la voce di menù principale "Programma" utilizza i settaggi di una attività di default che però non è visibile né  modificabile.

Un possibile comportamento corretto potrebbe essere:

- Ipotesi A: Il menù "Programma" viene rimosso, l'accesso all'editor di programmazione è disponibile solo caricando una "Attività"
- Ipotesi B: Il menù "Programma" rimane ma utilizza la configurazione di una "Attività" visibile nell'elenco attività, impostata come "default". In questo caso a mio avviso andrebbe prevista una Attività predefinita, "da impostazioni di Fabbrica" che non sia cancellabile né modificabile, che possa tornare a essere "default" nel caso l'utente cancelli (o semplicemente non crei) tutte le proprie Attività.

La soluzione "A" mi pare più in linea con il concetto di "Attività personalizzate" che è alla base di questa nuova UI, col rischio però di perdere leggermente in usabilità.

La soluzione "B" di fatto permette di non conoscere affatto il concetto di "Attività", al prezzo di essere forse un po' ridondante come UI.
