### ISSUE TITLE
Mancanza cestino

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/vue-app#31]
Non c’è il cestino per eliminare i blocchi nella parte di programmazione.

**Comment by avivace** [comment]
Non riesco a riprodurre, forse dipende dal resize della workspace di Blockly?
Prova a ridimensionare la finestra e vedere che succede.

Inoltre, manca solo il cestino ma i controlli dello zoom ci sono?

![localhost_5000_vue_index html](https://user-images.githubusercontent.com/14352721/49440687-9594ae80-f7c4-11e8-999b-e55e99cb9c30.png)

**Comment by leonardo77** [comment]
Anche mettendo la finestra a tutto schermo, arrivando quindi a visualizzare il bordo della canvas, continuano a mancare tutti i controlli (non solo il cestino).

**Comment by avivace** [comment]
Il caricamento di questi asset avviene da sorgenti remote, per questo l'issue non può essere riprodotto in presenza di connessione internet funzionante.

```
<image width="96" x="0" height="124" y="-32" clip-path="url(#blocklyTrashBodyClipPath9534499637565614)" xlink:href="https://blockly-demo.appspot.com/static/media/sprites.png"></image>
```
