### ISSUE TITLE
Codice AR/QR

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/vue-app#32]
Sarebbe carino avere una voce di menù da cui scaricare un PDF con i codici AR/QR che l'utente può stampare come sono o incorporare in altri immagini per fare esercizi di riconoscimento. Inoltre sarebbe carino far scaricare anche quelli che in genere usiamo noi (cartelli e frutta).

**Comment by avivace** [comment]
@previ hai a disposizione questi pdf?
@leonardo77 dove pensi debbano apparire i link che fanno scaricare questi PDF?

**Comment by leonardo77** [comment]
Potrebbe essere un piccolo link presente nella parte delle impostazioni oppure in basso sopra alle icone social, o ancora nella parte di definizione delle attività.

**Comment by previ** [comment]
Io li metterei a disposizione sul sito coderbot.org del resto per stamparli è necessario essere connessi alla rete di casa/ufficio quindi poterli scaricare direttamente dal bot non è strettamente necessario.

**Comment by leonardo77** [comment]
Ok, però metterei qualcosa nel Codebot che informi l'utente che può trovare i codici da stampare sul sito.

Forse terrei solamente i codice AR, almeno la mia esperienza con i codice QR è che il riconoscimento è molto più faticoso e potrebbe essere frustrante per l'utente. Credo comunque che nella maggior parte delle applicazioni i codici AR possano essere sufficienti...

**Comment by avivace** [comment]
PDF disponibile qui https://www.coderbot.org/repo/ . Ne verrà anche inclusa una versione localmente sull'applicazione web.
