### ISSUE TITLE
the "production" (dist release) files contains unnecessary resources

### ISSUE THREAD

**Issue by previ** [CoderBotOrg/vue-app#34]
In the dist resources several "/examples/" resources are present.

**Comment by avivace** [comment]
`find . -type d -name "*example*" -print` and `find . -name "*example*" -print` gives no directory or folders named `examples`.

The build however contains a lot of unnecessary assets related to the AR.js implementation, which is completely disabled atm. I'm going to clean that up.

**Comment by avivace** [comment]
This is a production build of 734a880
[vue-app-734a880.tar.gz](https://github.com/CoderBotOrg/vue-app/files/2649447/vue-app-734a880.tar.gz)

Does it look better?

**Comment by previ** [comment]
Yes, thanks.
