### ISSUE TITLE
Codice RGB pixel nelle foto della galleria

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/vue-app#37]
Sarebbe utile poter conoscere il codice RGB di un pixel su cui si clicca per una foto presente in galleria. 

Sarebbe ancora più utile poter fare un copia e poi incolla nel programma.

**Comment by avivace** [comment]
Per riferimento, ecco come era implementato nella vecchia versione dell'applicazione web:
https://github.com/CoderBotOrg/backend/blob/67f7aa155e0474c40c807e4e2f3c89080162f081/static/js/control.js#L90
