### ISSUE TITLE
Colore da codice RGB

### ISSUE THREAD

**Issue by leonardo77** [CoderBotOrg/vue-app#39]
Manca il comando per creare un colore, ad esempio da riconoscere, a partire dal suo codice RGB.

**Comment by previ** [comment]
Previous version implementation: https://github.com/CoderBotOrg/backend/blob/67f7aa155e0474c40c807e4e2f3c89080162f081/static/js/control.js#L90

**Comment by previ** [comment]
In effetti il comando esiste, nel senso che è sufficiente passare il [codice RGB in formato HTML/CSS](https://www.w3.org/wiki/CSS/Properties/color/keywords) in una casella di "testo" semplice.

Va certamente documentato meglio (in effetti manca una documentazione dei blocchi più complessi come quelli di visione artificiale), chiudo comunque questa issue.
