### ISSUE TITLE
Preferences Page should inform user when a Restart is needed

### ISSUE THREAD

**Issue by previ** [CoderBotOrg/vue-app#41]
Some parameters require a restart, the user should be advised and guided through the restart process.

**Comment by avivace** [comment]
Which parameters need a restart?

**Comment by previ** [comment]
> Which parameters need a restart?

I would say most settings, if not all of them.

**Comment by avivace** [comment]
> > Which parameters need a restart?
> 
> I would say most settings, if not all of them.

Okay, at that point it may be worth to just initiate the restart process for the user and wait for the coderbot to be up again?

**Comment by previ** [comment]
> Okay, at that point it may be worth to just initiate the restart process for the user and wait for the coderbot to be up again?

I must restate my previous assertion: most settings do not require a restart or at least not a full reboot.

It is therefore required to classify each setting (or group of setting) in "restart | reboot | no action" required.
