### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by avivace** [CoderBotOrg/vue-app#42]
@previ mentioned the application does not support i18n

I used and previously tried [vue-i18n](http://kazupon.github.io/vue-i18n/guide/started.html#javascript) and I think it suits our use case and it's very easy and straightforward to implement.

A set of critical points to consider follows:

- The strings in toolboxes from the legacy app were `{% trans %}` escaped and translated server side;
- Blockly supports i18n, we must pass the loaded locale while instancing the workspace;
- Blockly Toolboxes must be templat-able, they are actually static assets (convert them to JSON?);
- The locale will be loaded from the settings, we should move an application wide polling for those things in a resident/wrapper component (the sidebar?) and share those things in the vuex store;
- The language string files have to be separate and imported;

**Comment by avivace** [comment]
@previ maybe we can open a transifex page to track all the translation strings? I can help with Italian, French and English :)
Having fully translated locales could actually become a feature too (e.g. everything in Italian, but the teacher can decide to set the language to English for an Activity).

**Comment by previ** [comment]
@avivace good idea. Is it possible to use transfer for free? 
By the way, yes, I consider i18n as an important feature.
I was looking at vue-18n, it seems pretty streightforward.

**Comment by avivace** [comment]
Transifex should be [free](https://docs.transifex.com/projects/open-source-project) for open source projects. Another similar service it's crowdin but I'm not super sure about the differences

**Comment by previ** [comment]
Ok, I added the CoderBot organization and the "frontend" project, [here](https://www.transifex.com/coderbot/coderbot-frontend).
I uploaded an initial "Landing" messages just for testing, still to be integrated with the vue app (so format might change).

I also invited @avivace as an English translator using your old unimib email (still using it?).

Thanks for now, "well begun is half done"! :-)

**Comment by avivace** [comment]
> Ok, I added the CoderBot organization and the "frontend" project, [here](https://www.transifex.com/coderbot/coderbot-frontend). I uploaded an initial "Landing" messages just for testing, still to be integrated with the vue app (so format might change).
> 
> I also invited @avivace as an English translator using your old unimib email (still using it?).
> 
> Thanks for now, "well begun is half done"! :-)

Joined!

**Comment by previ** [comment]
Implemented in v0.4-beta1.

All text has been put in ./src/i18n/locales/<locale>/messages.json but at the moment only Italian is fully supported (other languages are just a placeholders.

As the coding part is (or should be) complete, I will close this issue and reopen separate ones for each locale we wish to support: en, fr (and possibly es, de or others in the future).
