### ISSUE TITLE
Not possible to add comments to blockly program

### ISSUE THREAD

**Issue by previ** [CoderBotOrg/vue-app#43]
When adding a comment on a code block (right click on block, select "add comment" menu), the comment popup is shown but it does not get the focus.

**Comment by avivace** [comment]
This is probably related to Chrome/how it renders `textarea` elements inside SVG.
It works as expected in Firefox:
![image](https://user-images.githubusercontent.com/14352721/50962623-f05bad00-14ca-11e9-8d1e-4485d72448b4.png)

**Comment by avivace** [comment]
Apparently, the `blocklyTotal` CSS class inherits `line-height: 0` form the parent div from the Vuetify styles (disabling `main.styl` fixes this).

This is one of the cases where Blockly depends on the default values, but they are overwritten by Vuetify, so forcing the Blockly CSS rules doesn't fix this, we need to re-apply the default values Blockly is expecting.

For now, `line-height: normal !important` fixes this.
