### ISSUE TITLE
Toolbox Editor

### ISSUE THREAD

**Issue by avivace** [CoderBotOrg/vue-app#45]
We must implement a way to define categories, blocks and everything that is currently in the XML toolbox definition with serializable and templatable objects.

Related to #42

**Comment by previ** [comment]
@avivace have you seen the [blockly toolbox example editor](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html)? (select tab "Workspace Factory")

**Comment by avivace** [comment]
This will influence #44 , too.
@previ I've seen that, but it heavily relies on Boostrap and JQuery. Currently working on something custom, manually defining and injecting blocks based on a JSON definition of the Toolbox.
