### ISSUE TITLE
Color and sorting of categories and blockls

### ISSUE THREAD

**Issue by meliurwen** [CoderBotOrg/vue-app#50]
Looking at the Blockly toolbar a couple of changes to propose came to my mind:

- Each category has assigned its own well distinguishable color.
- Categories should be listed in descending order by relevance (implying we have a definition of "relevant" in this context) form top to bottom; same thing for blocks within the categories.

If I remember correctly it's a pretty safe and easy thing to change (edit the _xml_ files in the `src/assets/` folder).

**Comment by avivace** [comment]
Makes a lot of sense and I think it'll be a nice quality of life improvement.

However - we are holding this up until #45 is implemented and there's a reproducible and usable way of editing toolboxes.

**Comment by previ** [comment]
related to #45 can be considered implemented in the toolbox editor
