### ISSUE TITLE
Wifi settings are missing

### ISSUE THREAD

**Issue by previ** [CoderBotOrg/vue-app#67]
It should be possible to configure the Wifi settings:

- Mode: Access Point or Client
- SSID name 
- Password

**Comment by avivace** [comment]
Yes, this would be nice! Just be sure that in case of failing to connect (what is a "failure"? How many connection attempts?) coderbot should fall back to the default network setup so the user is not locked out.

**Comment by previ** [comment]
> Yes, this would be nice! Just be sure that in case of failing to connect (what is a failing? How many connection attempts?) coderbot should fall back to the default network setup so the user is not locked out.

Correct, handling failures is the tricky part. Current implementation is possibly overly complex (many moving parts: hostapd, dnsmasq, dhcpcd, wpa_supplicant, etc) but it seems to work ... most of the times! :-)

**Comment by avivace** [comment]
> > Yes, this would be nice! Just be sure that in case of failing to connect (what is a failing? How many connection attempts?) coderbot should fall back to the default network setup so the user is not locked out.
> 
> Correct, handling failures is the tricky part. Current implementation is possibly overly complex (many moving parts: hostapd, dnsmasq, dhcpcd, wpa_supplicant, etc) but it seems to work ... most of the times! :-)

Do you think it could be simplified? Are there any of those components covered by something else now?

I remember it being quite consistent and reliable! I never had to ssh back in to restore the connection :)

**Comment by previ** [comment]
Implemented in v0.4-beta1
